#! /bin/sh

sxhkd &
bspc config focus_follows_pointer true
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# pywal
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# start applications
feh --bg-fill /home/asadik/Pictures/d9SEb.png
wal --theme vscode
$HOME/.config/polybar/launch.sh
compton --config ~/.compton -b
$HOME/.config/redshift.sh

# bind programs to workspaces
#assign [class="Signal"] 10
#assign [class="Slack"] 10
#exec slack
signal-desktop &
bspc rule -a Signal desktop=^10 follow=off
